name: Build

on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: |
          ./gradlew --no-daemon --warning-mode=all :library:assembleDebug :library:publishToMavenLocal :sample:assembleDebug
          echo "commit=$(echo ${{ github.sha }} | cut -c-7)" >> $GITHUB_ENV

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: welcome@${{ env.commit }}
          path: |
            library/build/outputs/aar/library-debug.aar
            sample/build/outputs/apk/debug/sample-debug.apk
